### ISSUE TITLE
Hurricane tracks issue - app crashes on BERYL/advisory 16 (app version v0.0.15).

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI/APSViz-UI-V3#113] opened 2024-07-12 12:09 UTC
The app crashes when hurricane advisory 16 is selected. the error shown in the console indicates an invalid GeoJSON data object.

this appears to be related to the catalog_member.member_def "layers" element is missing for the observation layer.

steps to reproduce:

- open the model selection tray
- select the BERYL tropical storm, hit submit.
- select the advisory 16.

this may be a known issue, but i didnt see an issue created for it.

**Comment by lstillwe** [comment] 2024-07-17 19:43
This was caused by some testing I was doing with load-geoserver. I have now updated DB with correct layers parameter.
Please check and close this issue, if fixed. Thanks!

**Comment by lstillwe** [comment] 2024-07-18 18:07
Closing issue

**Closed** 2024-07-18 18:08 UTC
